[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

# Add these for handling complex data like structs
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
